version: '2'
services:
  rabbit1:
    image: benyoo/rabbitmq:3.6.8-management
    container_name: rabbit1
    hostname: rabbit1
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_USER=dtopsrabbit
    - RABBITMQ_DEFAULT_PASS=dtopsrabbit

  rabbit2:
    image: benyoo/rabbitmq:3.6.8-management
    container_name: rabbit2
    hostname: rabbit2
    links:
    - rabbit1
    ports:
    - "5673:5672"
    - "15673:15672"
    environment:
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RAM_NODE=true
    - RABBITMQ_DEFAULT_USER=dtopsrabbit
    - RABBITMQ_DEFAULT_PASS=dtopsrabbit

  rabbit3:
    image: benyoo/rabbitmq:3.6.8-management
    container_name: rabbit3
    hostname: rabbit3
    links:
    - rabbit1
    - rabbit2
    ports:
    - "5674:5672"
    - "15674:15672"
    environment:
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RABBITMQ_DEFAULT_USER=dtopsrabbit
    - RABBITMQ_DEFAULT_PASS=dtopsrabbit